name: Release
on:
   push:
     tags: 
       - 'v*.*.*'  # 版本标签推送时触发发布

jobs:
  Release:
    name: build and release Electron app
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    permissions:
      issues: write
      models: read
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖
        run: npm install 
        env:
          ELECTRON_MIRROR: "https://npmmirror.com/mirrors/electron/"
 
      - name: Release for Windows
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ====================== 关键新增步骤 解决自动更新需要科学上网======================
      # 自动把更新文件传到你的国内云服务器
      - name: Upload to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          local-files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest.yml
          remote-host: ${{ secrets.SERVER_HOST }}
          remote-user: ${{ secrets.SERVER_USER }}
          remote-dir: /www/wwwroot/bluetools/
          ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}